

# Setup
title:            Bilal Naeem
tagline:          'Personal blog'
description:      'I plan on using this blog as a personal dev log'
url:              https://martianbilal.github.io/
baseurl:          "#"
paginate:         5

# About and contact
author:
  name:           'Bilal Naeem'
  url:            https://twitter.com/martianbilal

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
